# Generated by Django 5.0.9 on 2024-09-26 13:30

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('software_name', models.CharField(max_length=255)),
                ('software_description', models.TextField()),
                ('software_version', models.CharField(max_length=50, null=True)),
                ('software_years_of_use', models.PositiveIntegerField(default=1, null=True)),
                ('software_last_updated', models.DateField(null=True)),
                ('software_is_hosted', models.CharField(choices=[('INT', 'Internally'), ('EXT', 'Externally')], max_length=3)),
                ('software_is_tech_supported', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('software_is_cloud_based', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True)),
                ('software_maintenance_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('software_comments', models.TextField(blank=True, null=True)),
                ('software_number_of_licenses', models.PositiveIntegerField(blank=True)),
                ('software_to_operate', models.JSONField(default=api.models.Software.json_field_default)),
                ('hardware_to_operate', models.JSONField(default=api.models.Software.json_field_default)),
                ('software_annual_amount', models.FloatField(blank=True, max_length=10, null=True)),
                ('software_gl_accounts', models.CharField(blank=True, max_length=255, null=True)),
                ('software_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='api.department')),
                ('software_department_contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='api.contactperson')),
                ('software_divisions_using', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='api.division')),
                ('software_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softwares', to='api.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.software')),
            ],
        ),
    ]
