# Generated by Django 5.0.9 on 2024-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='name',
            new_name='contact_lastname',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='contact_name',
            field=models.CharField(default='Sofware Contact Person', max_length=100),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='contact_phone_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
