# Generated by Django 5.0.9 on 2024-09-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_contactperson_contact_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_expiration_date',
            field=models.DateField(null=True),
        ),
    ]
