# Generated by Django 5.0.9 on 2024-09-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_software_software_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='software_department',
        ),
        migrations.AddField(
            model_name='software',
            name='software_department',
            field=models.ManyToManyField(related_name='software', to='api.department'),
        ),
    ]
