# Generated by Django 5.0.9 on 2024-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_software_software_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareToOperate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareToOperate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_department_contact_person',
        ),
        migrations.AddField(
            model_name='software',
            name='software_department_contact_people',
            field=models.ManyToManyField(related_name='software_contact_people', to='api.contactperson'),
        ),
        migrations.RemoveField(
            model_name='software',
            name='hardware_to_operate',
        ),
        migrations.AlterField(
            model_name='software',
            name='software_department',
            field=models.ManyToManyField(related_name='software_deparments', to='api.department'),
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_divisions_using',
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_gl_accounts',
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_to_operate',
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_vendor',
        ),
        migrations.AddField(
            model_name='software',
            name='hardware_to_operate',
            field=models.ManyToManyField(related_name='hardware_to_operate', to='api.hardwaretooperate'),
        ),
        migrations.AddField(
            model_name='software',
            name='software_divisions_using',
            field=models.ManyToManyField(related_name='software_divisions', to='api.division'),
        ),
        migrations.AddField(
            model_name='software',
            name='software_gl_accounts',
            field=models.ManyToManyField(related_name='software_gl_accounts', to='api.glaccount'),
        ),
        migrations.AddField(
            model_name='software',
            name='software_to_operate',
            field=models.ManyToManyField(related_name='software_to_operate', to='api.softwaretooperate'),
        ),
        migrations.AddField(
            model_name='software',
            name='software_vendor',
            field=models.ManyToManyField(related_name='software_vendors', to='api.vendor'),
        ),
    ]
