# Generated by Django 5.0.9 on 2024-09-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_glaccount_hardwaretooperate_softwaretooperate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_operational_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
    ]
