# Generated by Django 5.0.9 on 2024-10-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_software_software_operational_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='software_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
