# Generated by Django 5.0.9 on 2024-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_software_software_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='hardware_to_operate',
            field=models.ManyToManyField(blank=True, related_name='hardware_to_operate', to='api.hardwaretooperate'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_department_contact_people',
            field=models.ManyToManyField(blank=True, related_name='software_contact_people', to='api.contactperson'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_divisions_using',
            field=models.ManyToManyField(blank=True, related_name='software_divisions', to='api.division'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_gl_accounts',
            field=models.ManyToManyField(blank=True, related_name='software_gl_accounts', to='api.glaccount'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_to_operate',
            field=models.ManyToManyField(blank=True, related_name='software_to_operate', to='api.softwaretooperate'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=50),
        ),
    ]
