# Generated by Django 5.0.9 on 2024-10-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_software_hardware_to_operate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='software_comments',
        ),
    ]
