# Generated by Django 5.0.9 on 2024-10-02 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_software_software_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='satisfaction_rate',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
