# Generated by Django 5.0.9 on 2024-10-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_contactperson_contact_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='contact_department',
        ),
    ]
