# Generated by Django 5.0.9 on 2024-10-10 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_contactperson_contact_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='contact_name',
            field=models.CharField(default='Software Contact Person', max_length=100),
        ),
    ]
