# Generated by Django 5.0.9 on 2024-10-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contactperson_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_is_cloud_based',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_is_hosted',
            field=models.CharField(choices=[('INT', 'Internally'), ('EXT', 'Externally')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_is_tech_supported',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
    ]
