# Generated by Django 5.0.9 on 2024-10-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_software_software_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='contact_phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
