# Generated by Django 5.0.9 on 2024-10-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_software_software_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='software',
            name='software_is_hosted',
            field=models.CharField(choices=[('INT', 'Internally'), ('EXT', 'Externally')], default='INT', max_length=3),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_maintenance_support',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
    ]
