# Generated by Django 5.0.9 on 2024-10-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_blacklistedtoken_alter_software_software_is_hosted_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['token'], name='api_blackli_token_e48c7b_idx'),
        ),
    ]
