# Generated by Django 5.0.9 on 2024-11-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_blacklistedtoken_api_blackli_token_e48c7b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_annual_amount_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_description',
            field=models.TextField(max_length=500),
        ),
    ]
