# Generated by Django 5.0.9 on 2025-01-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_software_software_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
